language: node_js
script: npm run test
notifications:
  email: false
  slack:
    secure: H+BPVkyTUPbo5RVVeLsP7AjP9uxkJuTBfq7WoVjexOC3umkuU2LD2nKpNhgNbl2gQ7CnbUANxpwHmD57gpVrn6xgF/o/gMEyEZ07knSkjQSIdcSzuAQsTh7S5u/z3XwG6qk6QqHd0ucyUIyYiyNjG9zg9W4rhzfeKqD33GunFPXSBcNit4LF+MggueiavNARA4IM/GaXjWiqv4HH2SQuk45VSP/PKJwZVz/oHJYZtV79ua6xwzz+8OwMOeLXUUikvFMdDwiT8nUi6V88rGrmYQvNWkWriZdLIpgqM4qEHpHBRocarTW0JRVCYTkTwKtibinfSjtQYgVSB2fFhNDMvGtFvPiwjF7Opy74tvSBdgO3IUD0GUprxszjDDLhbXWoovwLRqpQhX22RkaO/oRCqLOpDKbwJfoZq3ghnjSRAsw3xUAFfyw3eU0B41viVJDXQsu4TiCB9ttZinJERlmkej5zJdZH/zdSn7uZ5xEhP7W/mk1V5Ha1wEk098Uj4HsAekHgY3VVUhXWJ/yTM0aWGPS0WfphphRo259rDMGxslUs3MLGQpW1x1Hxg2FsLXb2Y7bvVeVHFLb7kxFQ/rGENMMQ/FzpjMSomWZ1zdEusKK1IbgYLBl8v3xNo6X1Y17d7nDmVByChm5AQ7JengVFVWatdJzMGF4bjUPe1ai/l8w=
